# Generated by Django 3.1.3 on 2020-11-11 13:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e0655f0a-c58a-4b86-8f29-2c0e2a04f3e9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
