# Generated by Django 3.1.3 on 2020-11-11 16:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_auto_20201111_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e1e00991-5bc2-4178-a61b-e5468de00a12'), editable=False, primary_key=True, serialize=False),
        ),
    ]
