# Generated by Django 3.1.3 on 2020-12-03 04:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_auto_20201111_2222'),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiveAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=600)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignment', to='college.subject')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.AlterField(
            model_name='uploadedassignment',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='assignments.giveassignment'),
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
