# Generated by Django 3.1.3 on 2020-12-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_auto_20201203_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadassignment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
