# Generated by Django 3.1.3 on 2020-12-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_uploadassignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadassignment',
            name='uploaded_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
